name = "CellMLToolkit"
uuid = "03cb29e0-1ef4-4721-aa24-cf58a006576f"
authors = ["Shahriar Iravanian <siravan@svtsim.com>"]
version = "1.2.0"

[deps]
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
LightXML = "0.9.0"
ModelingToolkit = "3.14.1"
OrdinaryDiffEq = "5.42.0"
julia = "1.3"
