name = "CellMLToolkit"
uuid = "03cb29e0-1ef4-4721-aa24-cf58a006576f"
authors = ["Shahriar Iravanian <siravan@svtsim.com>"]
version = "2.3.2"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
IfElse = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173"
MathML = "abcecc63-2b08-419c-80c4-c63dca6fa478"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
EzXML = "1.1"
HTTP = "0.9"
MathML = "0.1"
Memoize = "0.4"
ModelingToolkit = "5.14.1"
OrdinaryDiffEq = "5.52"
SymbolicUtils = "0.10.2"
julia = "1.5"

[extras]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ModelingToolkit", "OrdinaryDiffEq", "JSON3"]
